function [prediction_output, c_t_01_output, h_t_01_output, c_t_03_output, h_t_03_output] = model_classify(input, model, c_t_01, h_t_01, c_t_03, h_t_03)

[c_t_01, h_t_01] = lstm_layer(input, ...
                              h_t_01, ...
                              c_t_01, ...
                              model.Layer_01.W_i, ... 
                              model.Layer_01.W_f, ...
                              model.Layer_01.W_c, ...
                              model.Layer_01.W_o, ...
                              model.Layer_01.U_i, ...
                              model.Layer_01.U_f, ...
                              model.Layer_01.U_c, ...
                              model.Layer_01.U_o, ...
                              model.Layer_01.b_i, ...
                              model.Layer_01.b_f, ...
                              model.Layer_01.b_c, ...
                              model.Layer_01.b_o);

[c_t_03, h_t_03] = lstm_layer(h_t_01, ...
                              h_t_03, ...
                              c_t_03, ...
                              model.Layer_03.W_i, ... 
                              model.Layer_03.W_f, ...
                              model.Layer_03.W_c, ...
                              model.Layer_03.W_o, ...
                              model.Layer_03.U_i, ...
                              model.Layer_03.U_f, ...
                              model.Layer_03.U_c, ...
                              model.Layer_03.U_o, ...
                              model.Layer_03.b_i, ...
                              model.Layer_03.b_f, ...
                              model.Layer_03.b_c, ...
                              model.Layer_03.b_o);                                  

dense_layer05_output = relu(dense_layer(h_t_03, ...
                                        model.Layer_05.W, ...
                                        model.Layer_05.b));
                              
prediction = sigmoid(dense_layer(dense_layer05_output, ...
                                 model.Layer_06.W, ...
                                 model.Layer_06.b));

prediction_output = prediction;
c_t_01_output = c_t_01;
h_t_01_output = h_t_01;
c_t_03_output = c_t_03;
h_t_03_output = h_t_03;
end

